### ISSUE TITLE
Create Sprite for Captain's Hat

### ISSUE THREAD

**Issue by doficia** [doficia/project-cordon-sprites#106]
Please see CONTRIBUTING.md first.

**Comment by Laxaor** [comment]
Does "captain's hat" mean the typical boat captain hat? (kind of like the police one 👮 but white on top)

**Comment by doficia** [comment]
Hi @Laxaor! Yes, that is right. And you just reminded me that I also wanted to create an issue for a General Hat, thanks. :smile:

**Comment by Laxaor** [comment]
No problem, thanks for the clarification! I'll be adding this sprite shortly 😉
