### ISSUE TITLE
Create Sprite for Baseball Bat

### ISSUE THREAD

**Issue by doficia** [doficia/project-cordon-sprites#128]
Please see CONTRIBUTING.md first.

**Comment by Leila-Albrecht** [comment]
![baseball-bat](https://user-images.githubusercontent.com/32477127/31133879-950dacda-a858-11e7-9d46-3b4d5c907b21.png)

Hey! I've never done this before so I doubt that it's what you're looking for, but you're welcome to use it if it looks ok!

**Comment by doficia** [comment]
Hi @JadeDiablo! This is very good actually. :smiley: I think you should submit this as a pull request so that it counts towards your score in Hacktoberfest.

**Comment by Leila-Albrecht** [comment]
I'm a complete noob at this, only made an account today! Trying to figure out how to make a pull request but I don't know how to do it yet. But thanks for liking my image! ^^

**Comment by doficia** [comment]
@JadeDiablo welcome to GitHub then! :smiley: Well you can take your time to figure it out, I'll leave this open so that you can grab your loot for it later. :smiley:
