### ISSUE TITLE
Create Sprite for Gas Mask

### ISSUE THREAD

**Issue by doficia** [doficia/project-cordon-sprites#150]
Please see CONTRIBUTING.md first.

As pointed out by @Laxaor, there is already a gasmask.png in this repository.

An armored or heavy variant would be fine here, but you are also free to get creative!

**Comment by Laxaor** [comment]
There's a gas mask sprite already [sprites/armors/gasmask.png]. Should this issue be relabelled as update instead of create?

**Comment by doficia** [comment]
Since we are going for a post-apocalyptic theme, we kind of need more variants of gas masks - they will be very iconic items. Create is fine here, there will also be an update for the previous version - sorry for the miscommunication.
