### ISSUE TITLE
Create Sprite for Train Tracks (Horizontally Tileable) (Decoration)

### ISSUE THREAD

**Issue by doficia** [doficia/project-cordon-sprites#288]
**Please see CONTRIBUTING.md first.**

Happy Hacking! :smiley:

**Comment by V1rtURL** [comment]
I'm interested in creating this for you, here's the end result: 

![train-tracks-horizontal](https://user-images.githubusercontent.com/15385889/31309847-1133927a-ab5b-11e7-98b6-ee2c6f17b0b4.png)

Not sure what you meant by horizontally, when you have 3/4 isometric as part of your label:world.

**Comment by doficia** [comment]
Hi @Smokeweaver! Did you create the ground tile as well? I am asking because it looks pretty nice, and was wondering if you had a clean version of it without the tracks. :smiley:
