### ISSUE TITLE
Create Sprite for Grass Tile Variant

### ISSUE THREAD

**Issue by doficia** [doficia/project-cordon-sprites#299]
**Please see CONTRIBUTING.md first.**

Happy Hacking! :smiley:

**Comment by cxong** [comment]
What is this issue about? There's already a grass tile here: https://github.com/doficia/project-cordon-sprites/blob/master/sprites/tiles/grass.png

**Comment by doficia** [comment]
Hi @cxong! By variant I mean an alternative to an existing one, so when tiled it does not look so dull or repetitive.
