### ISSUE TITLE
Create Sprite for Gravel Tile

### ISSUE THREAD

**Issue by doficia** [doficia/project-cordon-sprites#300]
**Please see CONTRIBUTING.md first.**

Happy Hacking! :smiley:

**Comment by V1rtURL** [comment]
I cleaned the train tracks off, set it to the tile parameters (64x64px) here's the result: 

![gravel-tile](https://user-images.githubusercontent.com/15385889/31309937-b22d5bce-ab5c-11e7-89f9-de3fcc3dcda4.png)

**Comment by doficia** [comment]
Nice, thanks. :smiley:
