### ISSUE TITLE
Create Sprite for Gas Mask

### ISSUE THREAD

**Issue by doficia** [doficia/project-cordon-sprites#336]
**Please see CONTRIBUTING.md first.**

Happy Hacking! :smiley:

**Comment by oyvindjam** [comment]
Hey, I can work on this one :smile:

**Comment by doficia** [comment]
Hi @oyvindjam! That would be great. :)

**Comment by oyvindjam** [comment]
Hey! @doficia 
There is already a sprite for gasmask under sprites/armors/.
Should I replace the exsisting one or should I create a new file for my attempt?
Since mine has quite a different style it might be useful to keep both.

**Comment by doficia** [comment]
Hi @oyvindjam! Gas Masks are going to be very iconic items, so more alternatives are fine! Keeping both would be great. Thank you!
