### ISSUE TITLE
Create Sprite for Blowtorch

### ISSUE THREAD

**Issue by doficia** [doficia/project-cordon-sprites#381]
**Please see CONTRIBUTING.md first.**

Happy Hacking! :smiley:

**Comment by abhishek71994** [comment]
Can you tell me a bit more precisely how to implement that? I would like to work on this.

**Comment by doficia** [comment]
Hi @abhishek71994! The blowtorch is going to be a weapon, something like a clumsy and small flamethrower. If you Google blowtorch, you will get several great reference images. Which one you choose - up to your liking. 

Once you have the idea how it should look I suggest you draw some monocolor outlines until you get the shape right. I'd pick the dominant colors after that and fill the sprite's surface with that palette. No detailes, just marking the areas.

Finally you could decide upon a light source and add highlights and shadows - if shading looks clumsy or sharp try anti-aliasing or dithering maybe. I'm no expert, there are plenty of techniques I suppose. :)

**Comment by abhishek71994** [comment]
This will be a png file? or a psd?

**Comment by doficia** [comment]
Definitely PNG. :smiley:

**Comment by abhishek71994** [comment]
the size wiil be an icon?

**Comment by doficia** [comment]
Yes.

**Comment by abhishek71994** [comment]
Okay I'll try to make one using PS. First time for everything.... I'll stay close to the guidelines.

**Comment by doficia** [comment]
Welcome to pixel art then! PS is fine, PiskelApp is an online tool specifically for pixel art - it is free, you can check out - but you choose your tools of course. I'm not rejecting for the quality of the sprite so no worries if your first try does not turn out as the most amazing art ever made. :smiley:

**Comment by abhishek71994** [comment]
![blow-torch](https://user-images.githubusercontent.com/8072400/31384797-328eb65e-adde-11e7-8678-86769a7d37a9.png)
So I came up with this.. I'm sure you'd like some improvements?

**Comment by doficia** [comment]
No, the outline is great. It is totally recognizable!  You can go ahead. :smiley:

**Comment by abhishek71994** [comment]
I'll start with the coloring and detail then. I'll fork and PR by 23:00 IST(I hope to).

**Comment by doficia** [comment]
Take as much time as you need. No deadlines. :smiley:

**Comment by abhishek71994** [comment]
I'm gonna make a PR, I think I am done. One is with flames the other is without one.

**Comment by abhishek71994** [comment]
Where is a blow-torch gonna go? Weapon?

**Comment by doficia** [comment]
Yes. Thank you!
