### ISSUE TITLE
Create Sprite for Kusarigama

### ISSUE THREAD

**Issue by doficia** [doficia/project-cordon-sprites#94]
Please see CONTRIBUTING.md first.

**Comment by FlavioFS** [comment]
OMG! 'Can I has' kusarigama???! :sparkles: :grin: :sparkles:

**Comment by doficia** [comment]
With that attitude? Absolutely! :smile:

**Comment by FlavioFS** [comment]
Done. I am uploading it soon.

**Comment by doficia** [comment]
Super nice! Thank you @FlavioFS! :smile: :confetti_ball:
