### ISSUE TITLE
Create Sprite for Flamethrower

### ISSUE THREAD

**Issue by doficia** [doficia/project-cordon-sprites#97]
Please see CONTRIBUTING.md first.

**Comment by Akatsuki06** [comment]
I am up for this! What kind of sprites I should add ? Any?

**Comment by doficia** [comment]
Hi @Akatsuki06! I am not sure what you mean, but as long as it matches our style described in CONTRIBUTING.md, 'any' should be fine. :smiley:

**Comment by Akatsuki06** [comment]
Ok!
